### ISSUE TITLE
Version for gnuradio 3.10

### ISSUE THREAD

**Issue by Kitoko86** [drmpeg/gr-dvbc#5]
Hi,

Could you provide an updated version of gr-dvbc for gnuradio 3.10, please ? Your project will deserve more interest from my point of view. I own a bladeRF and a LimeSDR and I would like to test them with your software. 

Best Regards.

**Comment by drmpeg** [comment]
Sure, no problem. Give me a day or two.

**Comment by drmpeg** [comment]
Okay, it's ready. Let me know if you have any issues.

**Comment by Kitoko86** [comment]
Thank you.

I have successfully compiled this version. I could give you some feedback about it when I'll have more spare time. Anyway, I close the issue for now.
